### ISSUE TITLE
Events Gallery

### ISSUE THREAD

**Issue by getaclue00** [sesa-uottawa/uottawasesa#24]
Let's work on having a simple gallery section on our website.
I'm going to try a simple, bruce force way at first... and then work on a more elegant solution.... if we want that.

The plan is to create a generic view and use the controller to serve the view based on the pictures of an event. Hopefully, it will be executed via simple route rules.

**Comment by charle692** [comment]
I think the original idea behind the gallery was to use Instagram. And we would add all our photos on there. Not sure if I misunderstood though.

**Comment by getaclue00** [comment]
I have nothing against that, it would be much easier for me to upload them to our website, have them showcased to the public automatically, and have them available for downloads (and adjustments) for Instagram.

But, if you guys don't want a Gallery and would rather have Instagram feed, then its all good.

**Comment by charle692** [comment]
Right, ok well I'll let Kat and Craig decide on this.

**Comment by CraigBryan** [comment]
Uploading them to the website may be an issue, as we are still running Heroku. We can't really have an image gallery by uploading them via git (in the code), because that become messy. It'd be better to have the images uploaded with some kind of form, and stored in database (or otherwise on the server).

Things may change when we move the site to a uottawa server, also.
