### ISSUE TITLE
Do we want to have a sub reddit?

### ISSUE THREAD

**Issue by katdrobnjakovic** [sesa-uottawa/uottawasesa#25]

**Comment by CraigBryan** [comment]
Do we think it'll be used?  I mean, people could post things, but I don't see those being any different than what goes on the facebook page. 

What could be interesting is having a subreddit as a cross-club space to share things (with the CS clubs and whatnot).

**Comment by katdrobnjakovic** [comment]
not sure. just saw that the cs club had one already.

**Comment by CraigBryan** [comment]
What's the subreddit name? Is it active?

**Comment by getaclue00** [comment]
Its alright. It is mostly them just posting and sharing links with each other.

https://www.reddit.com/r/csclub

**Comment by vpetkar** [comment]
I think the Reddit community for U of O is very inactive/weak, and it might be partially because of fragmentation into subreddits which this would contribute to. It could be argued that CS/SEG are much more active on Reddit than any other demographic though, which might find some value in having this subreddit.

**Comment by CraigBryan** [comment]
We have discussed this partially internally, and there was little to no interest. I think this is a no-go.
